# Pod que consume claves individuales de un Secret como variables de entorno
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: "postgres.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "myapp_db"
  DB_USER: "admin"
  DB_PASSWORD: "SecurePassword123!"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-env-individual
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: busybox
    command: 
    - sh
    - -c
    - |
      echo "=== Database Configuration ==="
      echo "Host: $DATABASE_HOST"
      echo "Port: $DATABASE_PORT"
      echo "Database: $DATABASE_NAME"
      echo "User: $DATABASE_USER"
      echo "Password: $DATABASE_PASSWORD"
      echo ""
      echo "=== Connection String ==="
      echo "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME"
      echo ""
      echo "Sleeping..."
      sleep 3600
    
    # Mapear claves individuales del Secret a variables de entorno
    env:
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_HOST
    
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_PORT
    
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_NAME
    
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_USER
    
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_PASSWORD

  restartPolicy: Never

---
# Comandos de verificación:
# kubectl apply -f pod-env-individual.yaml
# kubectl logs app-env-individual
# kubectl exec app-env-individual -- env | grep DATABASE
# kubectl delete pod app-env-individual
# kubectl delete secret db-credentials
