# Pod simple con NGINX
# Uso: kubectl apply -f pod-nginx.yaml
# Acceso: kubectl port-forward pod/nginx-simple 8080:80

apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple
  labels:
    app: nginx
    example: "true"
    category: basico
  annotations:
    description: "Pod simple con NGINX Alpine para testing"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
