# Múltiples Pods con diferentes labels para demostrar selectors
# Uso: kubectl apply -f pods-con-labels.yaml
# Filtrar: kubectl get pods -l app=frontend
#          kubectl get pods -l environment=production

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-prod
  labels:
    app: frontend
    environment: production
    tier: web
    version: "1.0"
    example: "true"
    category: labels-demo
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-dev
  labels:
    app: frontend
    environment: development
    tier: web
    version: "1.0"
    example: "true"
    category: labels-demo
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-prod
  labels:
    app: backend
    environment: production
    tier: api
    version: "2.0"
    example: "true"
    category: labels-demo
spec:
  containers:
  - name: python
    image: python:alpine
    command: ['sh', '-c', 'python -m http.server 8080']
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-dev
  labels:
    app: backend
    environment: development
    tier: api
    version: "2.0"
    example: "true"
    category: labels-demo
spec:
  containers:
  - name: python
    image: python:alpine
    command: ['sh', '-c', 'python -m http.server 8080']
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Pod
metadata:
  name: database-prod
  labels:
    app: database
    environment: production
    tier: data
    version: "1.0"
    example: "true"
    category: labels-demo
spec:
  containers:
  - name: postgres
    image: postgres:alpine
    env:
    - name: POSTGRES_PASSWORD
      value: "demo123"
    - name: POSTGRES_DB
      value: "myapp"
    ports:
    - containerPort: 5432
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
