# =============================================================================
# Ejemplo 02: Pod con Múltiples Contenedores
# =============================================================================
#
# Los recursos del Pod son la SUMA de los recursos de todos sus contenedores
#
# Recursos totales de este Pod:
# - Requests: cpu=500m, memory=256Mi
# - Limits:   cpu=1, memory=512Mi
# =============================================================================

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-resources
  labels:
    app: demo
    example: multi-container
spec:
  containers:
  
  # Contenedor principal - aplicación web
  - name: web
    image: nginx:1.25-alpine
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80
  
  # Contenedor sidecar - recolector de logs
  - name: log-collector
    image: busybox:1.36
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Log collector starting..."
        while true; do
          echo "$(date): Collecting logs..."
          sleep 10
        done
    resources:
      requests:
        cpu: "250m"      # ← Se SUMA al request del contenedor web
        memory: "128Mi"
      limits:
        cpu: "500m"      # ← Se SUMA al limit del contenedor web
        memory: "256Mi"

# =============================================================================
# CÁLCULO DE RECURSOS TOTALES
# =============================================================================
#
# Pod total = SUM(all containers)
#
# Requests totales:
#   CPU:    250m (web) + 250m (log-collector) = 500m
#   Memory: 128Mi (web) + 128Mi (log-collector) = 256Mi
#
# Limits totales:
#   CPU:    500m (web) + 500m (log-collector) = 1000m (1 CPU)
#   Memory: 256Mi (web) + 256Mi (log-collector) = 512Mi
#
# =============================================================================
# COMANDOS ÚTILES
# =============================================================================
#
# Aplicar:
# kubectl apply -f pod.yaml
#
# Ver recursos por contenedor:
# kubectl top pod multi-container-resources --containers
#
# Ver recursos totales:
# kubectl describe pod multi-container-resources | grep -A 15 "Containers:"
#
# Limpiar:
# kubectl delete -f pod.yaml
