# Access Mode: ReadOnlyMany (ROX)
# Múltiples nodos pueden montar el volumen en modo solo lectura

# Escenario: Distribuir datos estáticos/configuraciones a múltiples Pods
# 1. Un Job escribe datos en un volumen RWO
# 2. Se cambia el PVC a ROX
# 3. Múltiples Pods leen los datos

# PASO 1: PVC inicial con ReadWriteOnce para escritura
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-preparation
  labels:
    purpose: initial-load
spec:
  accessModes:
    - ReadWriteOnce  # ← Inicialmente RWO para escribir
  
  storageClassName: managed-csi
  
  resources:
    requests:
      storage: 20Gi

---
# PASO 2: Job que prepara datos (escritura)
apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader
  labels:
    purpose: initial-load
spec:
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      restartPolicy: OnFailure
      containers:
      - name: loader
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "=== Job: Preparando datos iniciales ==="
          echo ""
          
          # Crear estructura de directorios
          mkdir -p /data/config
          mkdir -p /data/assets
          mkdir -p /data/reference
          
          # Crear archivos de configuración
          cat > /data/config/app.conf <<EOF
          # Configuración de la aplicación
          APP_NAME=MyDistributedApp
          VERSION=1.0.0
          ENVIRONMENT=production
          LOG_LEVEL=info
          EOF
          
          # Crear datos de referencia
          echo "=== Datos de referencia ===" > /data/reference/data.txt
          for i in $(seq 1 100); do
            echo "Registro $i: $(date +%s)" >> /data/reference/data.txt
          done
          
          # Crear assets estáticos
          echo "Logo SVG aquí" > /data/assets/logo.svg
          echo "Hoja de estilos CSS" > /data/assets/styles.css
          echo "JavaScript bundle" > /data/assets/app.js
          
          echo ""
          echo "=== Datos preparados exitosamente ==="
          echo "Estructura creada:"
          find /data -type f
          echo ""
          echo "Tamaño total:"
          du -sh /data
          
          echo ""
          echo "✅ Datos listos para ser leídos en modo ROX"
        
        volumeMounts:
        - name: data-volume
          mountPath: /data
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-data-preparation

---
# PASO 3: PVC con ReadOnlyMany para lectura distribuida
# ⚠️ Aplicar DESPUÉS de que el Job complete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-readonly-data
  labels:
    purpose: readonly-distribution
spec:
  accessModes:
    - ReadOnlyMany  # ← Modo solo lectura
  
  storageClassName: azurefile-csi  # ⚠️ Azure Files soporta ROX
  
  resources:
    requests:
      storage: 20Gi

---
# PASO 4: Deployment con múltiples réplicas leyendo datos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-readonly-consumers
  labels:
    purpose: readonly-distribution
spec:
  replicas: 5  # ← Múltiples réplicas en diferentes nodos
  selector:
    matchLabels:
      app: readonly-consumer
  template:
    metadata:
      labels:
        app: readonly-consumer
    spec:
      containers:
      - name: consumer
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "=== Consumer Pod (ReadOnlyMany) ==="
          echo "Pod: $(hostname)"
          echo "Nodo: $NODE_NAME"
          echo ""
          
          # Leer configuración
          echo "=== Configuración de la aplicación ==="
          cat /data/config/app.conf
          echo ""
          
          # Verificar que NO se puede escribir
          echo "=== Intentando escribir (debe fallar) ==="
          if echo "test" > /data/test.txt 2>/dev/null; then
            echo "❌ ERROR: Se pudo escribir (no debería)"
          else
            echo "✅ CORRECTO: Escritura bloqueada (read-only)"
          fi
          echo ""
          
          # Leer datos de referencia
          echo "=== Primeras 10 líneas de datos de referencia ==="
          head -10 /data/reference/data.txt
          echo ""
          
          # Listar assets
          echo "=== Assets disponibles ==="
          ls -lh /data/assets/
          echo ""
          
          # Simular aplicación leyendo datos periódicamente
          while true; do
            echo "$(date): Procesando datos desde $(hostname)..."
            # Aplicación lee datos pero no escribe
            wc -l /data/reference/data.txt
            sleep 30
          done
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        volumeMounts:
        - name: readonly-data
          mountPath: /data
          readOnly: true  # ← Forzar modo solo lectura en el montaje
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      volumes:
      - name: readonly-data
        persistentVolumeClaim:
          claimName: pvc-readonly-data

# Casos de uso para ReadOnlyMany:
#
# ✅ Distribuir configuraciones estáticas a múltiples Pods
# ✅ Compartir assets estáticos (imágenes, CSS, JS)
# ✅ Datos de referencia que no cambian (catálogos, diccionarios)
# ✅ Machine Learning: distribuir modelos entrenados
# ✅ CDN interno: archivos estáticos para múltiples frontends

# Flujo típico:
# 1. Escribir datos con PVC RWO (Job/Pod de carga)
# 2. Crear PVC ROX apuntando a los mismos datos
# 3. Deployments leen datos sin riesgo de modificación
# 4. Actualización: repetir proceso con nuevo Job

# ⚠️ Nota sobre Azure:
# ReadOnlyMany requiere Azure Files (azurefile-csi)
# Azure Disk NO soporta ROX

# Para probar (proceso de 2 fases):
#
# FASE 1: Preparar datos
# kubectl apply -f rox-readonlymany.yaml
# # Solo aplica el Job y pvc-data-preparation
#
# Esperar a que el Job complete:
# kubectl get jobs data-loader
# kubectl wait --for=condition=complete job/data-loader --timeout=120s
#
# Ver logs del Job:
# kubectl logs job/data-loader
# # Debe mostrar "Datos preparados exitosamente"
#
# FASE 2: Distribuir en modo ROX
# # Comentar Job y pvc-data-preparation
# # Descomentar pvc-readonly-data y Deployment
# kubectl apply -f rox-readonlymany.yaml
#
# Ver Pods consumidores:
# kubectl get pods -l app=readonly-consumer -o wide
# # 5 Pods, posiblemente en diferentes nodos
#
# Ver logs de un consumer:
# kubectl logs -l app=readonly-consumer --tail=30 --prefix
# # Debe mostrar configuración leída
# # Debe mostrar "✅ CORRECTO: Escritura bloqueada"
#
# Intentar escribir desde un Pod (debe fallar):
# POD=$(kubectl get pod -l app=readonly-consumer -o jsonpath='{.items[0].metadata.name}')
# kubectl exec $POD -- sh -c 'echo "test" > /data/test.txt'
# # Error: Read-only file system ✅
#
# Verificar distribución multi-nodo:
# kubectl get pods -l app=readonly-consumer -o custom-columns=NAME:.metadata.name,NODE:.spec.nodeName
#
# Limpiar:
# kubectl delete -f rox-readonlymany.yaml

# Alternativa: Usar ConfigMap/Secret para datos pequeños
# ReadOnlyMany es mejor para:
# - Datos grandes (> 1MB)
# - Binarios (modelos ML, imágenes)
# - Datos que cambian ocasionalmente pero deben ser consistentes
