# Access Mode: ReadWriteMany (RWX)
# Múltiples nodos pueden montar el volumen simultáneamente en modo lectura-escritura

# PVC con Azure Files - Soporta ReadWriteMany
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwx-files
  labels:
    access-mode: rwx
spec:
  accessModes:
    - ReadWriteMany  # ← Múltiples nodos pueden montar simultáneamente
  
  storageClassName: azurefile-csi  # Azure Files (no Azure Disk)
  
  resources:
    requests:
      storage: 100Gi

---
# Deployment con múltiples réplicas - ✅ Funciona perfectamente con RWX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rwx-writers
  labels:
    demo: rwx
spec:
  replicas: 5  # ← Múltiples réplicas pueden estar en diferentes nodos
  selector:
    matchLabels:
      app: rwx-demo
      role: writer
  template:
    metadata:
      labels:
        app: rwx-demo
        role: writer
    spec:
      containers:
      - name: writer
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "=== Writer Pod con ReadWriteMany ==="
          echo "Pod: $(hostname)"
          echo "Nodo: $NODE_NAME"
          echo ""
          
          # Crear directorio para este Pod
          mkdir -p /shared/pods/$(hostname)
          
          # Escribir datos continuamente
          while true; do
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
            echo "$TIMESTAMP - Pod: $(hostname) - Nodo: $NODE_NAME" >> /shared/pods/$(hostname)/data.log
            echo "$TIMESTAMP - Pod: $(hostname) - Nodo: $NODE_NAME" >> /shared/global.log
            
            echo "Escribí en /shared/pods/$(hostname)/data.log"
            echo "Total de Pods escribiendo: $(ls -1 /shared/pods/ | wc -l)"
            
            sleep 10
          done
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: pvc-rwx-files

---
# Deployment de lectores - También pueden acceder simultáneamente
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rwx-readers
  labels:
    demo: rwx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rwx-demo
      role: reader
  template:
    metadata:
      labels:
        app: rwx-demo
        role: reader
    spec:
      containers:
      - name: reader
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "=== Reader Pod con ReadWriteMany ==="
          echo "Pod: $(hostname)"
          echo "Nodo: $NODE_NAME"
          echo ""
          
          while true; do
            echo "==============================================="
            echo "Timestamp: $(date)"
            echo ""
            
            # Listar todos los Pods que están escribiendo
            echo "=== Pods detectados ==="
            ls -1 /shared/pods/
            echo ""
            
            # Mostrar últimas líneas del log global
            echo "=== Últimas 10 entradas del log global ==="
            if [ -f /shared/global.log ]; then
              tail -10 /shared/global.log
            else
              echo "⚠️ Log global no existe todavía"
            fi
            
            echo ""
            sleep 15
          done
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
          # readOnly: true  # ← Descomentar si quieres lectores en modo solo lectura
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: pvc-rwx-files

---
# Service para acceder a los writers
apiVersion: v1
kind: Service
metadata:
  name: rwx-writers
  labels:
    demo: rwx
spec:
  type: ClusterIP
  selector:
    app: rwx-demo
    role: writer
  ports:
  - port: 80
    targetPort: 8080

# Ventajas de ReadWriteMany:
# ✅ Múltiples Pods en diferentes nodos pueden leer/escribir simultáneamente
# ✅ Ideal para aplicaciones que comparten archivos (CMS, media processing, logs)
# ✅ Permite escalado horizontal sin problemas de volúmenes
# ✅ Deployments pueden tener muchas réplicas
#
# Casos de uso:
# - WordPress con múltiples réplicas compartiendo uploads/
# - Aplicaciones de procesamiento de medios
# - Logs centralizados accesibles desde múltiples Pods
# - Configuraciones compartidas que se actualizan dinámicamente

# ⚠️ Limitaciones en Azure:
# ReadWriteMany SOLO funciona con Azure Files (azurefile-csi)
# NO funciona con Azure Disk (managed-csi, managed-csi-premium)

# Para probar:
# kubectl apply -f rwx-readwritemany.yaml
#
# Ver PVC:
# kubectl get pvc pvc-rwx-files
# # Debe estar Bound
#
# Ver todos los Pods:
# kubectl get pods -l app=rwx-demo -o wide
# # Deberías ver 5 writers + 3 readers = 8 Pods
# # Pueden estar en diferentes nodos ✅
#
# Ver logs de un writer:
# kubectl logs -l role=writer --tail=20 --prefix
# # Múltiples Pods escribiendo datos
#
# Ver logs de un reader:
# kubectl logs -l role=reader --tail=30
# # Debe mostrar actividad de todos los writers
#
# Acceder a un reader y explorar:
# READER_POD=$(kubectl get pod -l role=reader -o jsonpath='{.items[0].metadata.name}')
# kubectl exec -it $READER_POD -- sh
# ls -lh /shared/pods/
# # Deberías ver directorios de los 5 writers
# cat /shared/global.log | tail -20
# # Entradas de todos los Pods
# exit
#
# Verificar que Pods están en diferentes nodos:
# kubectl get pods -l app=rwx-demo -o custom-columns=NAME:.metadata.name,NODE:.spec.nodeName
# # ✅ Si tienes múltiples nodos, verás distribución
#
# Escalar writers:
# kubectl scale deployment app-rwx-writers --replicas=10
# kubectl get pods -l role=writer -o wide
# # ✅ Todos los Pods funcionan, sin importar en qué nodo estén
#
# Ver volumeattachments:
# kubectl get volumeattachment
# # Azure Files puede estar montado en múltiples nodos simultáneamente
#
# Limpiar:
# kubectl delete -f rwx-readwritemany.yaml

# Comparación RWO vs RWX:
#
# ReadWriteOnce (Azure Disk):
# - Un solo nodo puede montar
# - Alto rendimiento (SSD)
# - Bajo costo
# - Mejor para bases de datos single-instance
#
# ReadWriteMany (Azure Files):
# - Múltiples nodos pueden montar
# - Rendimiento moderado (file share)
# - Costo más alto
# - Mejor para aplicaciones distribuidas con archivos compartidos
