# ejemplos/01-serviceaccount-completo.yaml
# Service Account con todas las configuraciones posibles
#
# Este ejemplo muestra un Service Account completo con:
# - Metadata completa (labels, annotations)
# - ImagePullSecrets para registros privados
# - Control de montaje automático del token
#
# Uso: kubectl apply -f 01-serviceaccount-completo.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aplicacion-backend
  namespace: produccion
  
  # Labels para organización y filtrado
  labels:
    app: backend
    environment: production
    team: platform
    version: v1.0
  
  # Annotations para documentación adicional
  annotations:
    description: "SA para backend API con acceso a ConfigMaps y Secrets"
    contact: "backend-team@empresa.com"
    created-by: "devops-team"
    security-level: "high"

# Secretos para descargar imágenes de Azure Container Registry
# Esto permite que los pods que usan este SA puedan pull imágenes privadas
imagePullSecrets:
  - name: acr-secret

# Permitir montaje automático del token en pods
# Si es false, los pods que usan este SA NO tendrán acceso a la API
# a menos que monten el token manualmente
automountServiceAccountToken: true

---
# Secret para Azure Container Registry (ejemplo complementario)
# Este secret debe crearse con tus credenciales reales de ACR
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: produccion
type: kubernetes.io/dockerconfigjson
data:
  # El contenido debe ser el resultado de:
  # kubectl create secret docker-registry acr-secret \
  #   --docker-server=<tu-acr>.azurecr.io \
  #   --docker-username=<username> \
  #   --docker-password=<password> \
  #   --docker-email=<email> \
  #   --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6ImVtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RPSJ9fX0=

---
# NOTAS:
# 
# 1. Para crear este Service Account:
#    kubectl apply -f 01-serviceaccount-completo.yaml
#
# 2. Para verificar que se creó correctamente:
#    kubectl get sa aplicacion-backend -n produccion
#    kubectl describe sa aplicacion-backend -n produccion
#
# 3. Para crear un secret real de ACR:
#    kubectl create secret docker-registry acr-secret \
#      --namespace=produccion \
#      --docker-server=miregistro.azurecr.io \
#      --docker-username=00000000-0000-0000-0000-000000000000 \
#      --docker-password=myPassword
#
# 4. Para usar este SA en un pod, agrega:
#    spec:
#      serviceAccountName: aplicacion-backend
