# ejemplos/03-serviceaccounts-por-ambiente.yaml
# Service Accounts organizados por ambiente
#
# Este ejemplo muestra cómo crear Service Accounts diferentes
# para cada ambiente (dev, staging, producción) con configuraciones
# y niveles de seguridad apropiados.
#
# Uso: kubectl apply -f 03-serviceaccounts-por-ambiente.yaml

# ============================================
# DESARROLLO - Configuración permisiva
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-dev
  namespace: desarrollo
  labels:
    environment: dev
    security-level: low
    team: developers
  annotations:
    description: "SA para ambiente de desarrollo - permisos amplios"
    purpose: "Testing y desarrollo rápido"

# Montaje automático habilitado para facilitar desarrollo
automountServiceAccountToken: true

---
# ============================================
# STAGING - Configuración intermedia
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-staging
  namespace: staging
  labels:
    environment: staging
    security-level: medium
    team: qa
  annotations:
    description: "SA para ambiente de staging - permisos moderados"
    purpose: "Testing de integración y QA"

automountServiceAccountToken: true

---
# ============================================
# PRODUCCIÓN - Configuración restrictiva
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-prod
  namespace: produccion
  labels:
    environment: production
    security-level: high
    team: platform
  annotations:
    description: "SA para producción - permisos mínimos necesarios"
    purpose: "Aplicación en producción con acceso restringido"
    compliance: "Cumple con políticas de seguridad corporativas"
    audit: "true"

# En producción, solo permitir lo estrictamente necesario
automountServiceAccountToken: true

# Secrets para pull de imágenes de producción desde ACR
imagePullSecrets:
  - name: acr-prod-secret

---
# NOTAS:
#
# 1. Cada ambiente tiene su propio namespace y Service Account
#
# 2. Los permisos específicos se asignan mediante Roles separados
#    (ver ejemplos 06-rbac-completo)
#
# 3. Desarrollo: permisos amplios para facilitar debugging
#    Staging: permisos similares a producción para testing realista
#    Producción: permisos mínimos según principio de least privilege
#
# 4. Para aplicar solo un ambiente específico:
#    kubectl apply -f 03-serviceaccounts-por-ambiente.yaml --namespace=desarrollo
#
# 5. Verificar todos los SAs creados:
#    kubectl get sa --all-namespaces | grep -E 'app-(dev|staging|prod)'
