# ejemplos/04-pod-con-serviceaccount.yaml
# Pod configurado para usar un Service Account específico
#
# Este ejemplo muestra cómo asignar un Service Account a un pod
# y verificar que el token se monta correctamente.
#
# Uso: kubectl apply -f 04-pod-con-serviceaccount.yaml

# Primero creamos el Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mi-app
  namespace: default
  labels:
    app: test-app

---
# Pod que usa el Service Account
apiVersion: v1
kind: Pod
metadata:
  name: test-sa-pod
  namespace: default
  labels:
    app: test-app
spec:
  # Especificar el Service Account a usar
  # Si se omite, se usa el SA "default" automáticamente
  serviceAccountName: mi-app
  
  containers:
  - name: test-container
    image: busybox:1.36
    
    # Comando que mantiene el pod corriendo
    command:
      - sleep
      - "3600"
    
    # Variables de entorno útiles para debugging
    env:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_SA
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName

---
# INSTRUCCIONES DE USO:
#
# 1. Aplicar este archivo:
#    kubectl apply -f 04-pod-con-serviceaccount.yaml
#
# 2. Verificar que el pod está corriendo:
#    kubectl get pod test-sa-pod
#
# 3. Verificar el Service Account asignado:
#    kubectl get pod test-sa-pod -o jsonpath='{.spec.serviceAccountName}'
#
# 4. Entrar al pod y verificar el token:
#    kubectl exec -it test-sa-pod -- sh
#
# 5. Dentro del pod, ejecutar:
#    # Ver el directorio con los secrets del SA
#    ls -la /var/run/secrets/kubernetes.io/serviceaccount/
#    
#    # Ver el namespace
#    cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
#    
#    # Ver el token (será un JWT largo)
#    cat /var/run/secrets/kubernetes.io/serviceaccount/token
#    
#    # Ver el certificado CA
#    cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#
# 6. Verificar variables de entorno:
#    kubectl exec test-sa-pod -- env | grep MY_POD
#
# 7. Limpiar recursos:
#    kubectl delete -f 04-pod-con-serviceaccount.yaml
