# ejemplos/05-pod-token-proyectado.yaml
# Pod con token de Service Account proyectado (más seguro)
#
# Los tokens proyectados son una característica de seguridad que proporciona:
# - Tokens con tiempo de expiración
# - Tokens específicos de audiencia
# - Renovación automática por el kubelet
#
# Recomendado para Kubernetes 1.20+
#
# Uso: kubectl apply -f 05-pod-token-proyectado.yaml

# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mi-app-segura
  namespace: default
  labels:
    security: enhanced

---
# Pod con token proyectado
apiVersion: v1
kind: Pod
metadata:
  name: pod-token-seguro
  namespace: default
  labels:
    app: secure-app
spec:
  serviceAccountName: mi-app-segura
  
  containers:
  - name: app
    image: nginx:alpine
    
    # Montar el token proyectado en una ubicación personalizada
    volumeMounts:
    - name: token
      mountPath: /var/run/secrets/tokens
      readOnly: true
    
    # Para debugging - mostrar contenido del token
    env:
    - name: TOKEN_PATH
      value: /var/run/secrets/tokens/token
  
  # Definir el volumen con el token proyectado
  volumes:
  - name: token
    projected:
      # Múltiples fuentes pueden combinarse aquí
      sources:
      # Token del Service Account con configuración avanzada
      - serviceAccountToken:
          # Ruta del archivo dentro del volumen
          path: token
          
          # Token expira en 1 hora (3600 segundos)
          # El kubelet lo renovará automáticamente
          expirationSeconds: 3600
          
          # Audiencia específica - para qué servicio es válido el token
          # Útil para tokens específicos de servicio
          audience: api

---
# Pod alternativo con múltiples tokens proyectados
apiVersion: v1
kind: Pod
metadata:
  name: pod-multi-token
  namespace: default
spec:
  serviceAccountName: mi-app-segura
  
  containers:
  - name: app
    image: busybox:1.36
    command: ["sleep", "3600"]
    
    volumeMounts:
    # Token para API de Kubernetes
    - name: kube-api-token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
    
    # Token para servicio externo
    - name: external-service-token
      mountPath: /var/run/secrets/external
      readOnly: true
  
  volumes:
  # Token para API de Kubernetes (expiración 1 hora)
  - name: kube-api-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 3600
          audience: api
      # También incluir el CA cert y namespace
      - configMap:
          name: kube-root-ca.crt
          items:
          - key: ca.crt
            path: ca.crt
      - downwardAPI:
          items:
          - path: namespace
            fieldRef:
              fieldPath: metadata.namespace
  
  # Token para servicio externo (expiración 30 minutos)
  - name: external-service-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 1800
          audience: external-service

---
# NOTAS:
#
# 1. Ventajas de tokens proyectados:
#    - Más seguros (expiran automáticamente)
#    - Se renuevan automáticamente antes de expirar
#    - Pueden ser específicos de audiencia
#    - Reducen riesgo de tokens robados
#
# 2. Para aplicar:
#    kubectl apply -f 05-pod-token-proyectado.yaml
#
# 3. Verificar el token dentro del pod:
#    kubectl exec -it pod-token-seguro -- sh
#    cat /var/run/secrets/tokens/token
#
# 4. Para ver la expiración del token (requiere jwt-cli o similar):
#    kubectl exec pod-token-seguro -- cat /var/run/secrets/tokens/token | jwt decode -
#
# 5. El kubelet renovará automáticamente el token cuando esté cerca de expirar
#
# 6. Comparar con montaje estándar:
#    # Token estándar (no expira)
#    kubectl exec pod-token-seguro -- ls /var/run/secrets/kubernetes.io/serviceaccount/
#    
#    # Token proyectado (expira)
#    kubectl exec pod-token-seguro -- ls /var/run/secrets/tokens/
#
# 7. Limpiar:
#    kubectl delete -f 05-pod-token-proyectado.yaml
