# ejemplos/07-clusterrole-serviceaccount.yaml
# Service Account con ClusterRole para permisos globales
#
# A diferencia de Role (namespace-scoped), ClusterRole otorga
# permisos en TODOS los namespaces del cluster.
#
# Uso típico: Aplicaciones de monitoreo, operators, dashboards
#
# Uso: kubectl apply -f 07-clusterrole-serviceaccount.yaml

# ============================================
# Service Account en namespace específico
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-monitor
  namespace: monitoring
  labels:
    app: cluster-monitor
    scope: cluster-wide
  annotations:
    description: "SA para monitoreo global del cluster"
    security-level: "high"
    purpose: "Lectura de recursos en todos los namespaces"

---
# ============================================
# ClusterRole - Permisos en TODO el cluster
# ============================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-reader
  labels:
    app: cluster-monitor
  annotations:
    description: "Permisos de lectura de pods y namespaces en todo el cluster"

rules:
  # Lectura de pods en cualquier namespace
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  
  # Lectura de namespaces (recurso cluster-scoped)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  
  # Lectura de nodes (recurso cluster-scoped)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

---
# ============================================
# ClusterRoleBinding - Asocia SA con ClusterRole
# ============================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitor-binding
  labels:
    app: cluster-monitor
  annotations:
    description: "Otorga permisos de cluster-pod-reader al SA cluster-monitor"

subjects:
  # Service Account que recibe los permisos
  - kind: ServiceAccount
    name: cluster-monitor
    namespace: monitoring  # El SA existe en este namespace

roleRef:
  # ClusterRole que define los permisos
  kind: ClusterRole
  name: cluster-pod-reader
  apiGroup: rbac.authorization.k8s.io

---
# ============================================
# Pod de ejemplo usando el Service Account
# ============================================
apiVersion: v1
kind: Pod
metadata:
  name: cluster-monitor-pod
  namespace: monitoring
  labels:
    app: cluster-monitor
spec:
  serviceAccountName: cluster-monitor
  
  containers:
  - name: monitor
    image: bitnami/kubectl:latest
    command:
      - sleep
      - "3600"
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

---
# DIFERENCIAS: Role vs ClusterRole
#
# ┌────────────────────────────────────────────────────┐
# │                    Role                            │
# │  - Namespace-scoped                                │
# │  - Solo aplica en UN namespace                     │
# │  - Se usa con RoleBinding                          │
# │  - No puede acceder a recursos cluster-scoped      │
# └────────────────────────────────────────────────────┘
#
# ┌────────────────────────────────────────────────────┐
# │                 ClusterRole                        │
# │  - Cluster-scoped                                  │
# │  - Aplica en TODOS los namespaces                  │
# │  - Se usa con ClusterRoleBinding                   │
# │  - Puede acceder a recursos cluster-scoped         │
# │    (nodes, persistentvolumes, namespaces)          │
# └────────────────────────────────────────────────────┘
#
# VERIFICACIÓN:
#
# 1. Aplicar este archivo:
#    kubectl apply -f 07-clusterrole-serviceaccount.yaml
#
# 2. Verificar Service Account:
#    kubectl get sa cluster-monitor -n monitoring
#
# 3. Verificar ClusterRole:
#    kubectl get clusterrole cluster-pod-reader
#
# 4. Verificar ClusterRoleBinding:
#    kubectl get clusterrolebinding cluster-monitor-binding
#
# 5. Probar permisos en diferentes namespaces:
#    kubectl auth can-i get pods \
#      --as=system:serviceaccount:monitoring:cluster-monitor \
#      -n default
#    
#    kubectl auth can-i get pods \
#      --as=system:serviceaccount:monitoring:cluster-monitor \
#      -n kube-system
#    
#    # Ambos deberían devolver: yes
#
# 6. Probar desde el pod:
#    kubectl exec -it cluster-monitor-pod -n monitoring -- bash
#    
#    # Dentro del pod:
#    kubectl get pods --all-namespaces  # ✅ Funciona
#    kubectl get namespaces             # ✅ Funciona
#    kubectl get nodes                  # ✅ Funciona
#
# SEGURIDAD:
#
# ⚠️  ClusterRole otorga permisos amplios
# ⚠️  Usar solo cuando sea realmente necesario
# ⚠️  Preferir Role cuando sea posible
# ⚠️  Aplicar principio de mínimo privilegio
#
# LIMPIAR:
#    kubectl delete -f 07-clusterrole-serviceaccount.yaml
