# ejemplos/08-pod-custom-sa.yaml
# Ejemplos de pods con Service Accounts personalizados
#
# Muestra diferentes formas de configurar pods con Service Accounts
# y casos de uso comunes.
#
# Uso: kubectl apply -f 08-pod-custom-sa.yaml

# ============================================
# Service Account personalizado
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-app-sa
  namespace: default
  labels:
    app: custom-app

---
# ============================================
# EJEMPLO 1: Pod básico con SA personalizado
# ============================================
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-custom-sa
  namespace: default
  labels:
    app: custom-app
    example: basic
spec:
  # Especificar Service Account personalizado
  serviceAccountName: custom-app-sa
  
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

---
# ============================================
# EJEMPLO 2: Pod SIN Service Account (montaje deshabilitado)
# ============================================
apiVersion: v1
kind: Pod
metadata:
  name: pod-without-sa-token
  namespace: default
  labels:
    example: no-api-access
spec:
  # Usar el SA pero NO montar el token
  serviceAccountName: custom-app-sa
  automountServiceAccountToken: false
  
  containers:
  - name: static-app
    image: nginx:alpine
    
    # Esta aplicación NO necesita acceso a la API
    # Es solo un servidor web estático
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

---
# ============================================
# EJEMPLO 3: Pod con variables de entorno del SA
# ============================================
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa-env
  namespace: default
  labels:
    example: with-env-vars
spec:
  serviceAccountName: custom-app-sa
  
  containers:
  - name: app
    image: busybox:1.36
    command: ["sleep", "3600"]
    
    # Inyectar información del SA como variables de entorno
    env:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    
    - name: MY_POD_SA
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    
    - name: MY_POD_SA_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"

---
# ============================================
# EJEMPLO 4: Pod con token en ubicación personalizada
# ============================================
apiVersion: v1
kind: Pod
metadata:
  name: pod-custom-token-path
  namespace: default
  labels:
    example: custom-token-path
spec:
  serviceAccountName: custom-app-sa
  
  # Deshabilitar montaje automático
  automountServiceAccountToken: false
  
  containers:
  - name: app
    image: busybox:1.36
    command: ["sleep", "3600"]
    
    # Montar token en ubicación personalizada
    volumeMounts:
    - name: custom-token
      mountPath: /app/secrets
      readOnly: true
    
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
  
  volumes:
  - name: custom-token
    projected:
      sources:
      - serviceAccountToken:
          path: app-token
          expirationSeconds: 3600
          audience: my-app

---
# INSTRUCCIONES DE USO:
#
# 1. Aplicar todos los ejemplos:
#    kubectl apply -f 08-pod-custom-sa.yaml
#
# 2. Ver todos los pods creados:
#    kubectl get pods -l app=custom-app
#
# 3. EJEMPLO 1 - Verificar SA asignado:
#    kubectl get pod pod-with-custom-sa -o jsonpath='{.spec.serviceAccountName}'
#
# 4. EJEMPLO 2 - Verificar que NO hay token montado:
#    kubectl exec pod-without-sa-token -- ls /var/run/secrets/kubernetes.io/serviceaccount/
#    # Debería dar error o estar vacío
#
# 5. EJEMPLO 3 - Ver variables de entorno:
#    kubectl exec pod-with-sa-env -- env | grep MY_POD
#
#    Salida esperada:
#    MY_POD_NAMESPACE=default
#    MY_POD_NAME=pod-with-sa-env
#    MY_POD_SA=custom-app-sa
#    MY_POD_SA_UID=<uuid>
#
# 6. EJEMPLO 4 - Verificar token en ubicación personalizada:
#    kubectl exec pod-custom-token-path -- ls -la /app/secrets/
#    kubectl exec pod-custom-token-path -- cat /app/secrets/app-token
#
# CASOS DE USO:
#
# Ejemplo 1: Aplicación estándar que necesita acceso a la API
# Ejemplo 2: Aplicación que NO necesita API (mejor seguridad)
# Ejemplo 3: Aplicación que necesita saber su identidad
# Ejemplo 4: Aplicación con requerimientos específicos de token
#
# COMPARACIÓN DE ACCESO A LA API:
#
# ┌─────────────────┬──────────────┬────────────────────┐
# │ Pod             │ Token        │ Puede acceder API? │
# ├─────────────────┼──────────────┼────────────────────┤
# │ Ejemplo 1       │ ✅ Montado   │ ✅ Sí              │
# │ Ejemplo 2       │ ❌ No        │ ❌ No              │
# │ Ejemplo 3       │ ✅ Montado   │ ✅ Sí              │
# │ Ejemplo 4       │ ✅ Custom    │ ✅ Sí              │
# └─────────────────┴──────────────┴────────────────────┘
#
# LIMPIAR:
#    kubectl delete -f 08-pod-custom-sa.yaml
