# Pod production-ready con todas las mejores prácticas
# Uso: kubectl apply -f pod-completo.yaml
# Incluye: recursos, health probes, security context, labels

apiVersion: v1
kind: Pod
metadata:
  name: app-production
  labels:
    app: web-app
    tier: frontend
    environment: production
    version: v1.0.0
    managed-by: kubernetes
  annotations:
    description: "Pod production-ready con todas las configuraciones"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  # Security Context a nivel de Pod
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  
  containers:
  - name: web-server
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    
    # Variables de entorno
    env:
    - name: APP_ENV
      value: "production"
    - name: LOG_LEVEL
      value: "info"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    
    # Recursos definidos (requests y limits)
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    
    # Liveness Probe: verifica si el contenedor está vivo
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    
    # Readiness Probe: verifica si está listo para recibir tráfico
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    
    # Startup Probe: para aplicaciones con inicio lento
    startupProbe:
      httpGet:
        path: /startup
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 30  # 5s * 30 = 150s máximo para iniciar
    
    # Security Context a nivel de contenedor
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    
    # Volúmenes montados
    volumeMounts:
    - name: cache
      mountPath: /var/cache/nginx
    - name: run
      mountPath: /var/run
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  
  # Volumes
  volumes:
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  - name: config
    configMap:
      name: nginx-config
      optional: true
  
  # Restart policy
  restartPolicy: Always
  
  # DNS policy
  dnsPolicy: ClusterFirst
  
  # Tolerations (opcional - para nodos específicos)
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"

---
# ConfigMap para la configuración
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /healthz {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        location /ready {
            access_log off;
            return 200 "ready\n";
            add_header Content-Type text/plain;
        }
        
        location /startup {
            access_log off;
            return 200 "started\n";
            add_header Content-Type text/plain;
        }
    }
