# ejemplos/06-rbac-completo/01-serviceaccount.yaml
# Service Account para aplicación con permisos de lectura de pods
#
# Este es el primer paso de un conjunto de 3 archivos que muestran
# cómo implementar RBAC completo para un Service Account.
#
# Orden de aplicación:
# 1. Este archivo (Service Account)
# 2. 02-role.yaml (Definición de permisos)
# 3. 03-rolebinding.yaml (Asignación de permisos)
#
# Uso: kubectl apply -f 01-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: desarrollo
  
  labels:
    purpose: monitoring
    team: platform
    app: pod-monitor
  
  annotations:
    description: "Service Account para aplicación de monitoreo de pods"
    requires-permissions: "get, list pods"

---
# NOTAS:
#
# 1. Este Service Account por sí solo NO tiene permisos
#    Necesita un Role y RoleBinding (ver archivos 02 y 03)
#
# 2. Para verificar su creación:
#    kubectl get sa pod-reader -n desarrollo
#    kubectl describe sa pod-reader -n desarrollo
#
# 3. Para aplicar todo el conjunto de archivos:
#    kubectl apply -f ejemplos/06-rbac-completo/
