# Pod que usa imagePullSecrets para descargar im치genes de registro privado
# Primero crear el Secret con: ./create-registry-secret.sh

apiVersion: v1
kind: Pod
metadata:
  name: private-image-pod
spec:
  # Especificar Secret para pull de im치genes privadas
  imagePullSecrets:
  - name: my-registry-secret
  
  containers:
  - name: app
    # Imagen desde registro privado
    image: myregistry.example.com/myapp:v1.0.0
    command: ["sh", "-c", "echo 'App from private registry started' && sleep 3600"]

---
# Para configurar imagePullSecrets a nivel de ServiceAccount
# (todos los Pods que usen este SA heredar치n el Secret)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-serviceaccount
imagePullSecrets:
- name: my-registry-secret

---
# Deployment usando el ServiceAccount
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      # Usar ServiceAccount con imagePullSecrets configurado
      serviceAccountName: myapp-serviceaccount
      
      containers:
      - name: app
        # Imagen desde registro privado
        image: myregistry.example.com/myapp:latest
        ports:
        - containerPort: 8080

---
# Comandos de verificaci칩n:
#
# 1. Crear Secret de registry:
# ./create-registry-secret.sh
#
# 2. Aplicar este manifiesto:
# kubectl apply -f pod-imagepullsecrets.yaml
#
# 3. Verificar Pods:
# kubectl get pods
# kubectl describe pod private-image-pod
# (Buscar eventos de ImagePull)
#
# 4. Ver ServiceAccount:
# kubectl get sa myapp-serviceaccount -o yaml
# kubectl describe sa myapp-serviceaccount
#
# 5. Ver Deployment:
# kubectl get deployment private-registry-deployment
# kubectl describe deployment private-registry-deployment
#
# Limpiar:
# kubectl delete pod private-image-pod
# kubectl delete deployment private-registry-deployment
# kubectl delete serviceaccount myapp-serviceaccount
# kubectl delete secret my-registry-secret
