# ====================================================================
# REPLICASET CON MULTI-CONTAINER POD
# ====================================================================
# Descripción:
#   ReplicaSet que crea Pods con múltiples contenedores
#   Demuestra el patrón Sidecar (nginx + logger)
#
# Conceptos:
#   - Pods con múltiples contenedores
#   - Patrón Sidecar
#   - Volúmenes compartidos entre contenedores
#   - Template complejo
#
# Uso:
#   kubectl apply -f replicaset-multi-container.yaml
#   kubectl get pods -l app=webapp
#   kubectl logs <pod-name> -c nginx
#   kubectl logs <pod-name> -c logger
# ====================================================================

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  labels:
    app: webapp
    pattern: sidecar
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: webapp
  
  template:
    metadata:
      labels:
        app: webapp
        pattern: sidecar
    spec:
      # Volumen compartido entre contenedores
      volumes:
      - name: shared-logs
        emptyDir: {}
      
      containers:
      # Contenedor principal: nginx
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
        
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      
      # Contenedor sidecar: logger
      - name: logger
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          echo "Logger iniciado - monitoreando logs de nginx"
          while true; do
            if [ -f /logs/access.log ]; then
              tail -f /logs/access.log
            else
              echo "Esperando access.log..."
              sleep 5
            fi
          done
        
        volumeMounts:
        - name: shared-logs
          mountPath: /logs
          readOnly: true
        
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
