# 🏷️ UTS Namespace - COMPARTIDO
# Demuestra que todos los contenedores comparten hostname

apiVersion: v1
kind: Pod
metadata:
  name: uts-namespace-demo
  labels:
    demo: uts-namespace
    category: namespaces
spec:
  hostname: custom-pod-hostname  # Hostname personalizado
  subdomain: test-subdomain
  
  containers:
  - name: container1
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      echo ""
      echo "🏷️ UTS NAMESPACE - CONTAINER 1"
      echo "=============================="
      echo ""
      echo "Hostname:"
      hostname
      echo ""
      echo "FQDN (Fully Qualified Domain Name):"
      hostname -f 2>/dev/null || hostname
      echo ""
      echo "Domainname:"
      hostname -d 2>/dev/null || echo "(not set)"
      echo ""
      echo "Información del sistema:"
      uname -a
      
      sleep 3600
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    
  - name: container2
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      sleep 2
      echo ""
      echo "🏷️ UTS NAMESPACE - CONTAINER 2"
      echo "=============================="
      echo ""
      echo "Hostname:"
      hostname
      echo ""
      echo "FQDN:"
      hostname -f 2>/dev/null || hostname
      echo ""
      echo "Domainname:"
      hostname -d 2>/dev/null || echo "(not set)"
      echo ""
      echo "✅ Ambos contenedores comparten:"
      echo "   - Mismo hostname"
      echo "   - Mismo domainname"
      echo "   - Información del sistema (uname)"
      
      sleep 3600
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"

---
# Comandos para probar:
#
# 1. Crear el Pod:
# kubectl apply -f 04-uts-namespace.yaml
# kubectl wait --for=condition=Ready pod/uts-namespace-demo --timeout=60s
#
# 2. Verificar hostname desde container1:
# kubectl exec uts-namespace-demo -c container1 -- hostname
#
# 3. Verificar hostname desde container2:
# kubectl exec uts-namespace-demo -c container2 -- hostname
#
# 4. Ver logs:
# kubectl logs uts-namespace-demo -c container1
# kubectl logs uts-namespace-demo -c container2
#
# 5. Comparar información del sistema:
# kubectl exec uts-namespace-demo -c container1 -- uname -a
# kubectl exec uts-namespace-demo -c container2 -- uname -a
#
# 6. Verificar FQDN:
# kubectl exec uts-namespace-demo -c container1 -- hostname -f
# kubectl exec uts-namespace-demo -c container2 -- hostname -f
#
# Cleanup:
# kubectl delete pod uts-namespace-demo
