apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cpu-test
  template:
    metadata:
      labels:
        app: cpu-test
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "2"]
        resources:
          requests:
            cpu: "1000m"
