# =============================================================================
# Ejemplo 04: Pod-level Resources (Beta K8s 1.34+)
# =============================================================================
#
# Feature gate: PodLevelResources (enabled by default en K8s 1.34+)
#
# Permite especificar recursos a nivel de Pod en lugar de solo por contenedor.
# Útil cuando tienes muchos contenedores y es difícil calcular recursos exactos
# para cada uno.
#
# ⚠️ Solo soporta CPU y Memory (no ephemeral-storage, extended resources)
# =============================================================================

---
# Ejemplo 1: Solo Pod-level Resources
# Los contenedores comparten el presupuesto del Pod

apiVersion: v1
kind: Pod
metadata:
  name: pod-level-basic
  labels:
    example: pod-level-resources
    type: basic
spec:
  resources:  # ← A nivel de Pod
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  
  containers:
  - name: web
    image: nginx:1.25-alpine
    # Sin resources individuales
  
  - name: sidecar1
    image: busybox:1.36
    command: ["sleep", "infinity"]
  
  - name: sidecar2
    image: busybox:1.36
    command: ["sleep", "infinity"]

# Los 3 contenedores comparten: 2 CPU y 2 Gi memory

---
# Ejemplo 2: Pod-level + Container-level (Híbrido)
# Contenedor principal con límite, sidecars comparten el resto

apiVersion: v1
kind: Pod
metadata:
  name: pod-level-hybrid
  labels:
    example: pod-level-resources
    type: hybrid
spec:
  resources:  # Presupuesto total
    requests:
      cpu: "2"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "4Gi"
  
  containers:
  - name: app
    image: nginx:1.25-alpine
    resources:  # Límite individual
      limits:
        cpu: "2"      # ← Usa hasta 2 CPU
        memory: "2Gi"
    ports:
    - containerPort: 80
  
  - name: metrics-collector
    image: busybox:1.36
    command: ["sleep", "infinity"]
    # Sin resources → puede usar hasta (4-2)=2 CPU restantes
  
  - name: log-forwarder
    image: busybox:1.36
    command: ["sleep", "infinity"]
    # Comparte recursos con metrics-collector

# Validación: SUM(container.limits) <= pod.limits

---
# Ejemplo 3: Deployment con Pod-level Resources

apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-sidecar-app
  labels:
    example: pod-level-resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-sidecar
  template:
    metadata:
      labels:
        app: multi-sidecar
    spec:
      resources:  # Presupuesto del Pod
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "3"
          memory: "3Gi"
      
      containers:
      - name: app
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
      
      - name: prometheus-exporter
        image: prom/nginx-exporter:latest
        ports:
        - containerPort: 9113
      
      - name: fluentd
        image: fluent/fluentd:latest
      
      - name: istio-proxy
        image: istio/proxyv2:latest
      
      # Todos comparten 3 CPU y 3 Gi

---
# TESTING

# kubectl apply -f pod-level-resources.yaml
# kubectl get pods -l example=pod-level-resources
# kubectl describe pod pod-level-basic | grep -A 10 "Resources"
# kubectl top pod pod-level-basic --containers
