# ============================================================
# Patrón Init Container: Wait for Dependencies
# ============================================================
# Demuestra cómo usar init containers para esperar que
# múltiples servicios externos estén disponibles.
#
# Arquitectura:
#   - Init Container 1: Esperar Redis
#   - Init Container 2: Esperar PostgreSQL
#   - Init Container 3: Esperar API externa
#   - Main Container: Aplicación
#
# Flujo:
#   1. wait-for-redis espera hasta que Redis responda
#   2. wait-for-db espera hasta que PostgreSQL responda
#   3. wait-for-api espera hasta que API externa responda
#   4. app inicia solo si TODOS están disponibles
#
# Uso:
#   kubectl apply -f 02-init-wait-for-deps.yaml
#   kubectl get pods -w
#   kubectl logs app-wait-deps -c wait-for-redis
# ============================================================

apiVersion: v1
kind: Pod
metadata:
  name: app-wait-deps
  labels:
    app: dependent-app
    pattern: init-container
spec:
  # ============================================================
  # 🛠️ Init Containers (wait for dependencies)
  # ============================================================
  initContainers:
  
  # Init 1: Wait for Redis
  - name: wait-for-redis
    image: busybox:1.35
    command: ['sh', '-c']
    args:
      - |
        echo "⏳ Waiting for Redis at redis-service:6379..."
        
        until nc -z redis-service 6379; do
          echo "  Redis not available yet, waiting 2 seconds..."
          sleep 2
        done
        
        echo "✅ Redis is ready!"
    # Usa netcat (nc) para verificar si el puerto está abierto
  
  # Init 2: Wait for PostgreSQL (solo corre después de Init 1)
  - name: wait-for-db
    image: postgres:13
    command: ['sh', '-c']
    args:
      - |
        echo "⏳ Waiting for PostgreSQL at db-service:5432..."
        
        until pg_isready -h db-service -p 5432; do
          echo "  Database not available yet, waiting 2 seconds..."
          sleep 2
        done
        
        echo "✅ PostgreSQL is ready!"
  
  # Init 3: Wait for external API (solo corre después de Init 2)
  - name: wait-for-api
    image: curlimages/curl:7.85.0
    command: ['sh', '-c']
    args:
      - |
        echo "⏳ Waiting for API at api-service:8080/health..."
        
        MAX_RETRIES=30
        RETRY_COUNT=0
        
        until [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://api-service:8080/health || echo "000")
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ API is healthy! (HTTP $HTTP_CODE)"
            exit 0
          fi
          
          RETRY_COUNT=$((RETRY_COUNT + 1))
          echo "  API not ready yet (HTTP $HTTP_CODE), attempt $RETRY_COUNT/$MAX_RETRIES..."
          sleep 2
        done
        
        echo "❌ API did not become ready after $MAX_RETRIES attempts"
        exit 1
    # Usa curl para verificar endpoint de health check
    # Implementa retry logic con límite de intentos
  
  # ============================================================
  # 🌐 Main Container
  # ============================================================
  containers:
  - name: app
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=All dependencies are ready!"
      - "-listen=:8080"
    ports:
    - containerPort: 8080
    env:
    - name: REDIS_HOST
      value: "redis-service"
    - name: REDIS_PORT
      value: "6379"
    - name: DB_HOST
      value: "db-service"
    - name: DB_PORT
      value: "5432"
    - name: API_URL
      value: "http://api-service:8080"
    # La app puede asumir que TODOS los servicios están disponibles
    # No necesita lógica de retry o circuit breaking al iniciar
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 2
      periodSeconds: 5

---
# ============================================================
# Service para exponer la app
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: app-wait-deps-svc
spec:
  selector:
    app: dependent-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
