# ====================================================================
# PODS HUÉRFANOS - DEMOSTRACIÓN DE ADOPCIÓN
# ====================================================================
# Descripción:
#   Pods creados manualmente que pueden ser adoptados por un ReplicaSet
#   ⚠️ PELIGRO: Demuestra comportamiento peligroso de adopción
#
# Conceptos:
#   - Pods huérfanos (sin owner)
#   - Adopción por ReplicaSet
#   - Importancia de labels únicos
#
# Demo:
#   1. kubectl apply -f pods-huerfanos.yaml
#   2. kubectl get pods --show-labels
#   3. kubectl apply -f replicaset-adoption.yaml
#   4. kubectl get pods --show-labels
#   5. Observa cómo el ReplicaSet adopta los Pods
# ====================================================================

apiVersion: v1
kind: Pod
metadata:
  name: pod-huerfano-1
  labels:
    app: orphan-demo  # ← Este label será el problema
    created-by: manual
spec:
  containers:
  - name: nginx
    image: nginx:1.20-alpine  # ← Versión DIFERENTE
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-huerfano-2
  labels:
    app: orphan-demo  # ← Mismo label problemático
    created-by: manual
spec:
  containers:
  - name: nginx
    image: nginx:1.21-alpine  # ← Versión DIFERENTE
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-huerfano-3
  labels:
    app: orphan-demo  # ← Mismo label problemático
    created-by: manual
    extra-label: this-will-stay
spec:
  containers:
  - name: nginx
    image: nginx:alpine  # ← Sin versión específica
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
