# Secrets Inmutables con Estrategia de Versionamiento
# Los Secrets inmutables no se pueden modificar, solo eliminar y recrear
# Usamos nombres versionados para actualizaciones

# Versión 1 del Secret (inmutable)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-v1
  labels:
    app: myapp
    version: v1
type: Opaque
immutable: true  # No se puede modificar
stringData:
  username: "app_user_v1"
  password: "OldPassword123"
  host: "postgres-old.default.svc.cluster.local"

---
# Versión 2 del Secret (nueva versión con datos actualizados)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-v2
  labels:
    app: myapp
    version: v2
type: Opaque
immutable: true
stringData:
  username: "app_user_v2"
  password: "NewPassword456"
  host: "postgres-new.default.svc.cluster.local"
  connection-pool-size: "20"  # Nueva configuración

---
# Deployment inicial usando v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
  labels:
    app: myapp
    secret-version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      secret-version: v1
  template:
    metadata:
      labels:
        app: myapp
        secret-version: v1
    spec:
      containers:
      - name: app
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "=== Using Secret Version v1 ==="
          echo "Username: $DB_USERNAME"
          echo "Host: $DB_HOST"
          echo "Password: [REDACTED]"
          sleep 3600
        envFrom:
        - secretRef:
            name: db-credentials-v1  # Usando v1

---
# Deployment actualizado para usar v2 (nuevo manifiesto)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
  labels:
    app: myapp
    secret-version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      secret-version: v2
  template:
    metadata:
      labels:
        app: myapp
        secret-version: v2
    spec:
      containers:
      - name: app
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "=== Using Secret Version v2 ==="
          echo "Username: $username"
          echo "Host: $host"
          echo "Pool Size: $connection-pool-size"
          echo "Password: [REDACTED]"
          sleep 3600
        envFrom:
        - secretRef:
            name: db-credentials-v2  # Usando v2

---
# Comandos de gestión del ciclo de vida:
#
# 1. Desplegar versión 1:
# kubectl apply -f immutable-secrets-versioning.yaml
# kubectl rollout status deployment/myapp-v1
#
# 2. Verificar que v1 funciona:
# kubectl get pods -l secret-version=v1
# kubectl logs -l secret-version=v1 --tail=5
#
# 3. Intentar modificar Secret inmutable (fallará):
# kubectl edit secret db-credentials-v1
# Error: secrets "db-credentials-v1" is forbidden: immutable field
#
# 4. Desplegar nueva versión (blue-green deployment):
# kubectl apply -f myapp-v2-deployment.yaml
# kubectl rollout status deployment/myapp-v2
#
# 5. Verificar ambas versiones corriendo:
# kubectl get deployments -l app=myapp
# kubectl get pods -l app=myapp
#
# 6. Verificar que v2 funciona correctamente:
# kubectl logs -l secret-version=v2 --tail=5
#
# 7. Eliminar versión antigua:
# kubectl delete deployment myapp-v1
# kubectl delete secret db-credentials-v1
#
# Beneficios de esta estrategia:
# ✓ Rollback fácil (desplegar deployment con versión anterior)
# ✓ Blue-Green deployment (ambas versiones corriendo simultáneamente)
# ✓ Sin downtime durante actualizaciones
# ✓ Historial explícito de versiones
# ✓ Protección contra modificaciones accidentales (immutable)
