# Template de Secret con placeholders para uso con envsubst
# ⚠️ Este archivo SÍ es seguro para versionar en Git (no contiene credenciales reales)

apiVersion: v1
kind: Secret
metadata:
  name: secure-app-secret
  namespace: ${NAMESPACE:-default}
  labels:
    app: myapp
    environment: ${ENVIRONMENT}
type: Opaque
stringData:
  # Variables sustituidas desde entorno
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  
  API_KEY: ${API_KEY}
  API_SECRET: ${API_SECRET}
  
  JWT_SECRET: ${JWT_SECRET}
  ENCRYPTION_KEY: ${ENCRYPTION_KEY}
  
  # Variables con valores por defecto
  LOG_LEVEL: ${LOG_LEVEL:-info}
  APP_ENV: ${APP_ENV:-production}

---
# Instrucciones de uso:
#
# 1. Configurar variables de entorno (obtenerlas de un vault seguro):
# export NAMESPACE="production"
# export ENVIRONMENT="prod"
# export DB_HOST="postgres.production.svc.cluster.local"
# export DB_PORT="5432"
# export DB_NAME="myapp_prod"
# export DB_USER="app_user"
# export DB_PASSWORD="RealSecurePasswordFromVault123!"
# export API_KEY="sk_live_real_api_key_xyz789"
# export API_SECRET="real_api_secret_abc123"
# export JWT_SECRET="jwt_super_secret_key_do_not_share"
# export ENCRYPTION_KEY="aes256_encryption_key_32_chars"
#
# 2. Sustituir variables y aplicar:
# envsubst < secret-template.yaml | kubectl apply -f -
#
# 3. Verificar (NUNCA hacer esto en logs públicos):
# kubectl get secret secure-app-secret -o yaml
#
# 4. Para ver el resultado sin aplicar:
# envsubst < secret-template.yaml
#
# 5. Guardar en archivo temporal si es necesario:
# envsubst < secret-template.yaml > /tmp/secret-real.yaml
# kubectl apply -f /tmp/secret-real.yaml
# rm /tmp/secret-real.yaml  # Eliminar inmediatamente
#
# IMPORTANTE:
# - Este template SÍ se versiona en Git
# - Las variables de entorno NUNCA se versionan
# - Usar un secret manager (Vault, AWS Secrets Manager, etc.) para credenciales reales
