# =============================================================================
# QoS Class: BURSTABLE - Mixed (contenedores con diferentes configs)
# =============================================================================
#
# Cuando un Pod tiene múltiples contenedores con diferentes configuraciones
# de recursos, la QoS Class se calcula para TODO el Pod.
#
# Si AL MENOS UN contenedor no cumple con Guaranteed → Pod es Burstable
# =============================================================================

apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable-mixed
  labels:
    qos-class: burstable
    example: qos-demo
  annotations:
    description: "QoS: Burstable - contenedores con diferentes configs"
spec:
  containers:
  
  # Contenedor 1: request == limit (individual sería Guaranteed)
  - name: web
    image: nginx:alpine
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "128Mi"
    ports:
    - containerPort: 80
  
  # Contenedor 2: request < limit
  # Esto hace que TODO el Pod sea Burstable
  - name: sidecar
    image: busybox:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"      # ← Diferente a request
        memory: "256Mi"

# =============================================================================
# REGLA DE QoS PARA PODS CON MÚLTIPLES CONTENEDORES
# =============================================================================
#
# Para que un Pod sea Guaranteed, TODOS los contenedores deben cumplir:
#   - Tener requests Y limits para CPU y Memory
#   - requests == limits
#
# Si AL MENOS UN contenedor no cumple → Pod es Burstable
#
# En este ejemplo:
#   - Container 1 (web):     request == limit  ✅
#   - Container 2 (sidecar): request < limit   ❌
#
# Resultado: Pod completo = Burstable
#
# =============================================================================
# COMANDOS ÚTILES
# =============================================================================
#
# Aplicar:
# kubectl apply -f mixed.yaml
#
# Verificar QoS Class:
# kubectl get pod qos-burstable-mixed -o jsonpath='{.status.qosClass}'
# Output: Burstable
#
# Ver recursos por contenedor:
# kubectl top pod qos-burstable-mixed --containers
#
# Limpiar:
# kubectl delete -f mixed.yaml
