{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "advanced-templates.fullname" . }}
  labels:
    {{- include "advanced-templates.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "advanced-templates.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- range .Values.networkPolicy.policyTypes }}
  - {{ . }}
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
