# ====================================================================
# REPLICASET AUTO-RECUPERACIÓN (SELF-HEALING)
# ====================================================================
# Descripción:
#   ReplicaSet diseñado para demostrar auto-recuperación
#   Si eliminas un Pod, ReplicaSet crea uno nuevo automáticamente
#
# Conceptos:
#   - Auto-recuperación (self-healing)
#   - Reconciliación de estado
#   - Resiliencia
#
# Demo:
#   1. kubectl apply -f replicaset-auto-heal.yaml
#   2. kubectl get pods -l app=auto-heal --watch
#   3. En otra terminal:
#      POD=$(kubectl get pods -l app=auto-heal -o name | head -1)
#      kubectl delete $POD
#   4. Observa cómo se crea un nuevo Pod automáticamente
# ====================================================================

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auto-heal-rs
  labels:
    app: auto-heal
    demo: self-healing
spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: auto-heal
  
  template:
    metadata:
      labels:
        app: auto-heal
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        
        # Liveness probe agresivo para demostrar reinicio
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 2
        
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
        
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        
        # Variable de entorno para identificar el Pod
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
