{{- if .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-install
  labels:
    app: {{ .Chart.Name }}
    hook: pre-install
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-pre-install
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "=== PRE-INSTALL HOOK ==="
            echo "Release: {{ .Release.Name }}"
            echo "Namespace: {{ .Release.Namespace }}"
            echo "Preparando instalación..."
            sleep 2
            echo "Verificando requisitos..."
            echo "✅ Pre-install completado"
{{- end }}
