# =============================================================================
# Ejemplo 06: OOMKilled Simulation
# =============================================================================
# 
# Simula memory leak para demostrar comportamiento de OOMKilled
# ⚠️ SOLO PARA TESTING - NO usar en producción
# =============================================================================

---
# Ejemplo 1: Memory Leak Intencional

apiVersion: v1
kind: Pod
metadata:
  name: oomkilled-demo
  labels:
    example: troubleshooting
    type: oomkilled
  annotations:
    warning: "Este Pod será OOMKilled intencionalmente"
spec:
  restartPolicy: Always  # Se reiniciará tras OOMKill
  
  containers:
  - name: memory-hog
    image: polinux/stress
    command: ["stress"]
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "512M"    # Intenta usar 512MB
    - "--timeout"
    - "120s"
    
    resources:
      limits:
        memory: "256Mi"  # ← Límite menor que lo que intenta usar
      requests:
        memory: "128Mi"

# Comportamiento esperado:
# 1. Container intenta usar 512MB
# 2. Excede límite de 256Mi
# 3. Kernel OOM Killer termina el proceso
# 4. Exit Code: 137
# 5. Restart Count aumenta
# 6. Si falla repetidamente → CrashLoopBackOff

---
# Ejemplo 2: Memory Leak Gradual

apiVersion: v1
kind: Pod
metadata:
  name: gradual-memory-leak
  labels:
    example: troubleshooting
    type: memory-leak
spec:
  containers:
  - name: leaker
    image: busybox:1.36
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Starting gradual memory leak..."
        # Crea un array que crece indefinidamente
        i=0
        while true; do
          # Escribe a /dev/shm (tmpfs) para consumir memoria
          dd if=/dev/zero of=/dev/shm/file-$i bs=1M count=10 2>/dev/null
          i=$((i+1))
          echo "Allocated ${i}0 MB"
          sleep 2
        done
    
    resources:
      limits:
        memory: "256Mi"

---
# TESTING Y OBSERVACIÓN

# 1. Aplicar
# kubectl apply -f oomkilled-simulation.yaml

# 2. Ver estado (esperar ~30 segundos)
# kubectl get pod oomkilled-demo
# NAME             READY   STATUS             RESTARTS   AGE
# oomkilled-demo   0/1     CrashLoopBackOff   3          2m

# 3. Ver último estado
# kubectl describe pod oomkilled-demo | grep -A 10 "Last State"
# Last State:     Terminated
#   Reason:       OOMKilled
#   Exit Code:    137
#   Started:      ...
#   Finished:     ...

# 4. Ver restart count
# kubectl get pod oomkilled-demo -o jsonpath='{.status.containerStatuses[0].restartCount}'

# 5. Ver eventos
# kubectl get events --field-selector involvedObject.name=oomkilled-demo

# 6. Ver logs antes del crash
# kubectl logs oomkilled-demo --previous

# 7. Monitorear uso de memoria en tiempo real (otra terminal)
# while true; do kubectl top pod gradual-memory-leak; sleep 2; done
